### ISSUE TITLE
Review families not in COL

### ISSUE THREAD

**Issue by mdoering** [gbif/backbone-patch#10]
Asteraceae and Fabaceae are not accepted by COL and we should probably make them synonyms!

https://www.gbif.org/species/search?rank=FAMILY&dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=daacce49-b206-469b-8dc2-2257719f3afa&highertaxon_key=220&status=ACCEPTED&status=DOUBTFUL&advanced=1

See also https://github.com/gbif/portal-feedback/issues/3883

**Comment by mdoering** [comment]
This is not true. Both are accepted. They are just sourced to the backbone patch

**Comment by yroskov** [comment]
Incorrect. Names Asteraceae and Fabaceae accepted by CoL:
https://www.catalogueoflife.org/?taxonKey=622TP
https://www.catalogueoflife.org/?taxonKey=623QT
