### ISSUE TITLE
Synonym chosen over accepted name in match

### ISSUE THREAD

**Issue by peterdesmet** [gbif/backbone-patch#2]
This is probably more a match service issue, but the match for `Lamiastrum galeobdolon`: http://api.gbif.org/v1/species/match?verbose=false&name=Lamiastrum%20galeobdolon&strict=true

Is `Lamiastrum galeobdolon (L.) Ehrend. & Polatschek` (http://gbif.org/species/2927323) which is a synonym.

While `Lamium galeobdolon (L.) L.` (http://www.gbif.org/species/2927324), which is the accepted name, is an equally good match and probably preferred as a match.

**Comment by rdmpage** [comment]
@peterdesmet  I'm a little confused:

```
Lamiastrum galeobdolon - search term
Lamiastrum galeobdolon - hit (exact match)
Lamium galeobdolon - desired result (not exact match)
```

_Lamiastrum galeobdolon_ is a published name, albeit a synonym, so the result seems reasonable. Would you prefer to have _Lamiastrum galeobdolon_ returned as the hit, but the match would also provide the accepted name as well?

**Comment by peterdesmet** [comment]
Boy oh boy, must have been tired. 😪  Didn't see that the genus names differ. My mistake.

**Comment by rdmpage** [comment]
We've all been there ;)
