### ISSUE TITLE
Cercobarcon lasallei

### ISSUE THREAD

**Issue by kcopas** [gbif/backbone-patch#9]
[Newly described wasp species](https://doi.org/10.1080/00222933.2020.1747652) named for John La Salle

**Comment by mdoering** [comment]
I am slightly worried we start curating our own taxonomy here.
Is this new species critical to fix issues with occurrences or some other purpose? Whatever species we add we then need to monitor continuously in every build if the species is still considered valid. That burden should be limited to fixing serious or very prominent problems

**Comment by kcopas** [comment]
apologies—probably just missplaced a rando suggestion because of the ALA connection. Do with it what you will!

**Comment by timrobertson100** [comment]
I'll alert Plazi, which is the better place to manage these.

**Comment by mdoering** [comment]
Well, looking at COL it seems this wasp family is stale since 2009 and will not get updated easily:
https://data.catalogue.life/dataset/1068/meta

**Comment by mdoering** [comment]
But plazi articles will find its way into GBIF and COL soon too, so that is a good route!

**Comment by timrobertson100** [comment]
With thanks to our Plazi community 
https://www.gbif.org/dataset/search?q=lasallei&publishing_org=7ce8aef0-9e92-11dc-8738-b8a03c50a862
